// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPUvjg4D04JXCZJFihhlOndDob4M5XDGs',
    appId: '1:847066804234:web:44cba371f435442a336ff3',
    messagingSenderId: '847066804234',
    projectId: 'tripapp-5cf14',
    authDomain: 'tripapp-5cf14.firebaseapp.com',
    databaseURL: 'https://tripapp-5cf14-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tripapp-5cf14.appspot.com',
    measurementId: 'G-K8SY4HPS02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-b092Vpv2B2imSzn24MAvBAPKLXK9X78',
    appId: '1:847066804234:android:7da783e81a39312b336ff3',
    messagingSenderId: '847066804234',
    projectId: 'tripapp-5cf14',
    databaseURL: 'https://tripapp-5cf14-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tripapp-5cf14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAic-jg81aUUYwlxc9xyoG-D2n3TvI9p10',
    appId: '1:847066804234:ios:917f76e9441f4b37336ff3',
    messagingSenderId: '847066804234',
    projectId: 'tripapp-5cf14',
    databaseURL: 'https://tripapp-5cf14-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tripapp-5cf14.appspot.com',
    iosClientId: '847066804234-hdf7sh8d6bdf61iqskt5olgb74a2b4ub.apps.googleusercontent.com',
    iosBundleId: 'it.triptoshare.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAic-jg81aUUYwlxc9xyoG-D2n3TvI9p10',
    appId: '1:847066804234:ios:f06b955d8fa1e1ff336ff3',
    messagingSenderId: '847066804234',
    projectId: 'tripapp-5cf14',
    databaseURL: 'https://tripapp-5cf14-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tripapp-5cf14.appspot.com',
    iosClientId: '847066804234-fu9592m1gqtn4t6263cphrjudoqob11g.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripapp',
  );
}
